[21/7/2025, 1:16:42] INFO: Usuario registrado exitosamente {"usuario_id":"f7ff529b-7777-48c1-b0be-d6007e256a15","correo":"ejemplo@correo.com","ip_cliente":"::1"}
[21/7/2025, 1:30:58] INFO: Usuario registrado exitosamente {"usuario_id":"25680021-3b09-4333-b690-e22aecfba2a0","correo":"20221061@uthh.edu.mx","ip_cliente":"::ffff:127.0.0.1"}
[21/7/2025, 3:02:42] ERROR: Credenciales inv치lidas - Contrase침a incorrecta {"codigo_error":"400","ip_cliente":"::ffff:127.0.0.1","usuario":"luis2004hdez@gmail.com"}
[21/7/2025, 3:02:52] INFO: Inicio de sesi칩n exitoso {"usuario_id":"2b76e73a-2073-438b-b39f-ac2b7e152d4d","correo":"luis2004hdez@gmail.com","ip_cliente":"::ffff:127.0.0.1","fecha_hora":"21/7/2025, 3:02:52"}
[21/7/2025, 3:04:18] INFO: Sesi칩n cerrada {"ip_cliente":"::ffff:127.0.0.1"}
[21/7/2025, 3:19:50] ERROR: Validation error {"codigo_error":"500","stack":"Error\n    at Query.run (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\query.js:50:25)\n    at C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at async PostgresQueryInterface.insert (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\dialects\\abstract\\query-interface.js:308:21)\n    at async model.save (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\model.js:2490:35)\n    at async Usuario.create (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\model.js:1362:12)\n    at async registro (file:///C:/Users/luishdez/Desktop/puntoshein/backend/src/controllers/autenticacion.controller.js:78:26)","ip_cliente":"::ffff:127.0.0.1"}
[21/7/2025, 3:30:05] ERROR: Validation error {"codigo_error":"500","stack":"Error\n    at Query.run (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\query.js:50:25)\n    at C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\sequelize.js:315:28\n    at async PostgresQueryInterface.insert (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\dialects\\abstract\\query-interface.js:308:21)\n    at async model.save (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\model.js:2490:35)\n    at async Usuario.create (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\model.js:1362:12)\n    at async registro (file:///C:/Users/luishdez/Desktop/puntoshein/backend/src/controllers/autenticacion.controller.js:78:26)","ip_cliente":"::ffff:127.0.0.1"}
[21/7/2025, 3:59:09] ERROR: Validation error: Validation isEmail on correo failed {"codigo_error":"500","stack":"SequelizeValidationError: Validation error: Validation isEmail on correo failed\n    at InstanceValidator._validate (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\instance-validator.js:50:13)\n    at async InstanceValidator._validateAndRunHooks (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\instance-validator.js:60:7)\n    at async InstanceValidator.validate (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\instance-validator.js:54:12)\n    at async model.save (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\model.js:2426:7)\n    at async Usuario.create (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\model.js:1362:12)\n    at async registro (file:///C:/Users/luishdez/Desktop/puntoshein/backend/src/controllers/autenticacion.controller.js:143:26)","ip_cliente":"::ffff:127.0.0.1"}
[21/7/2025, 4:00:51] ERROR: Validation error: Validation isEmail on correo failed {"codigo_error":"500","stack":"SequelizeValidationError: Validation error: Validation isEmail on correo failed\n    at InstanceValidator._validate (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\instance-validator.js:50:13)\n    at async InstanceValidator._validateAndRunHooks (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\instance-validator.js:60:7)\n    at async InstanceValidator.validate (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\instance-validator.js:54:12)\n    at async model.save (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\model.js:2426:7)\n    at async Usuario.create (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\model.js:1362:12)\n    at async registro (file:///C:/Users/luishdez/Desktop/puntoshein/backend/src/controllers/autenticacion.controller.js:143:26)","ip_cliente":"::ffff:127.0.0.1"}
[21/7/2025, 4:01:11] ERROR: Validation error: Validation isEmail on correo failed {"codigo_error":"500","stack":"SequelizeValidationError: Validation error: Validation isEmail on correo failed\n    at InstanceValidator._validate (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\instance-validator.js:50:13)\n    at async InstanceValidator._validateAndRunHooks (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\instance-validator.js:60:7)\n    at async InstanceValidator.validate (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\instance-validator.js:54:12)\n    at async model.save (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\model.js:2426:7)\n    at async Usuario.create (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\model.js:1362:12)\n    at async registro (file:///C:/Users/luishdez/Desktop/puntoshein/backend/src/controllers/autenticacion.controller.js:143:26)","ip_cliente":"::ffff:127.0.0.1"}
[21/7/2025, 4:01:19] ERROR: Validation error: Validation isEmail on correo failed {"codigo_error":"500","stack":"SequelizeValidationError: Validation error: Validation isEmail on correo failed\n    at InstanceValidator._validate (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\instance-validator.js:50:13)\n    at async InstanceValidator._validateAndRunHooks (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\instance-validator.js:60:7)\n    at async InstanceValidator.validate (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\instance-validator.js:54:12)\n    at async model.save (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\model.js:2426:7)\n    at async Usuario.create (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\model.js:1362:12)\n    at async registro (file:///C:/Users/luishdez/Desktop/puntoshein/backend/src/controllers/autenticacion.controller.js:143:26)","ip_cliente":"::ffff:127.0.0.1"}
[21/7/2025, 4:01:40] ERROR: Validation error: Validation isEmail on correo failed {"codigo_error":"500","stack":"SequelizeValidationError: Validation error: Validation isEmail on correo failed\n    at InstanceValidator._validate (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\instance-validator.js:50:13)\n    at async InstanceValidator._validateAndRunHooks (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\instance-validator.js:60:7)\n    at async InstanceValidator.validate (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\instance-validator.js:54:12)\n    at async model.save (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\model.js:2426:7)\n    at async Usuario.create (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\model.js:1362:12)\n    at async registro (file:///C:/Users/luishdez/Desktop/puntoshein/backend/src/controllers/autenticacion.controller.js:143:26)","ip_cliente":"::ffff:127.0.0.1"}
[21/7/2025, 4:01:57] ERROR: Validation error: Validation isEmail on correo failed {"codigo_error":"500","stack":"SequelizeValidationError: Validation error: Validation isEmail on correo failed\n    at InstanceValidator._validate (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\instance-validator.js:50:13)\n    at async InstanceValidator._validateAndRunHooks (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\instance-validator.js:60:7)\n    at async InstanceValidator.validate (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\instance-validator.js:54:12)\n    at async model.save (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\model.js:2426:7)\n    at async Usuario.create (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\model.js:1362:12)\n    at async registro (file:///C:/Users/luishdez/Desktop/puntoshein/backend/src/controllers/autenticacion.controller.js:143:26)","ip_cliente":"::ffff:127.0.0.1"}
[21/7/2025, 4:02:08] ERROR: Validation error: Validation isEmail on correo failed {"codigo_error":"500","stack":"SequelizeValidationError: Validation error: Validation isEmail on correo failed\n    at InstanceValidator._validate (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\instance-validator.js:50:13)\n    at async InstanceValidator._validateAndRunHooks (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\instance-validator.js:60:7)\n    at async InstanceValidator.validate (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\instance-validator.js:54:12)\n    at async model.save (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\model.js:2426:7)\n    at async Usuario.create (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\model.js:1362:12)\n    at async registro (file:///C:/Users/luishdez/Desktop/puntoshein/backend/src/controllers/autenticacion.controller.js:143:26)","ip_cliente":"::ffff:127.0.0.1"}
[21/7/2025, 4:04:51] INFO: Sesi칩n cerrada {"ip_cliente":"::1"}
[21/7/2025, 4:04:51] INFO: Sesi칩n cerrada {"ip_cliente":"::1"}
[21/7/2025, 4:10:53] INFO: Inicio de sesi칩n exitoso {"usuario_id":"2b76e73a-2073-438b-b39f-ac2b7e152d4d","correo":"luis2004hdez@gmail.com","ip_cliente":"::ffff:127.0.0.1","fecha_hora":"21/7/2025, 4:10:53"}
[21/7/2025, 5:59:08] INFO: Sesi칩n cerrada {"ip_cliente":"::ffff:127.0.0.1"}
[21/7/2025, 5:59:08] INFO: Sesi칩n cerrada {"ip_cliente":"::ffff:127.0.0.1"}
[21/7/2025, 5:59:08] INFO: Sesi칩n cerrada {"ip_cliente":"::ffff:127.0.0.1"}
[21/7/2025, 6:05:43] INFO: Inicio de sesi칩n exitoso {"usuario_id":"2b76e73a-2073-438b-b39f-ac2b7e152d4d","correo":"luis2004hdez@gmail.com","ip_cliente":"::ffff:127.0.0.1","fecha_hora":"21/7/2025, 6:05:43"}
[21/7/2025, 6:05:51] INFO: Sesi칩n cerrada {"ip_cliente":"::ffff:127.0.0.1"}
[21/7/2025, 6:06:46] INFO: Inicio de sesi칩n exitoso {"usuario_id":"2b76e73a-2073-438b-b39f-ac2b7e152d4d","correo":"luis2004hdez@gmail.com","ip_cliente":"::ffff:127.0.0.1","fecha_hora":"21/7/2025, 6:06:46"}
[21/7/2025, 6:06:52] INFO: Sesi칩n cerrada {"ip_cliente":"::ffff:127.0.0.1"}
[21/7/2025, 6:07:18] ERROR: Credenciales inv치lidas - Contrase침a incorrecta {"codigo_error":"400","ip_cliente":"::ffff:127.0.0.1","usuario":"20221061@uthh.edu.mx"}
[21/7/2025, 6:09:23] INFO: Inicio de sesi칩n exitoso {"usuario_id":"aa7aeedc-9050-4532-bca4-3993bd631471","correo":"20221061@uthh.edu.mx","ip_cliente":"::ffff:127.0.0.1","fecha_hora":"21/7/2025, 6:09:23"}
[21/7/2025, 6:12:02] INFO: Sesi칩n cerrada {"ip_cliente":"::ffff:127.0.0.1"}
[21/7/2025, 6:12:02] INFO: Sesi칩n cerrada {"ip_cliente":"::ffff:127.0.0.1"}
[21/7/2025, 6:12:02] INFO: Sesi칩n cerrada {"ip_cliente":"::ffff:127.0.0.1"}
[21/7/2025, 6:12:20] INFO: Inicio de sesi칩n exitoso {"usuario_id":"aa7aeedc-9050-4532-bca4-3993bd631471","correo":"20221061@uthh.edu.mx","ip_cliente":"::ffff:127.0.0.1","fecha_hora":"21/7/2025, 6:12:20"}
[21/7/2025, 6:12:44] INFO: Sesi칩n cerrada {"ip_cliente":"::ffff:127.0.0.1"}
[21/7/2025, 6:12:44] INFO: Sesi칩n cerrada {"ip_cliente":"::ffff:127.0.0.1"}
[21/7/2025, 6:12:44] INFO: Sesi칩n cerrada {"ip_cliente":"::ffff:127.0.0.1"}
[21/7/2025, 6:14:56] INFO: Inicio de sesi칩n exitoso {"usuario_id":"aa7aeedc-9050-4532-bca4-3993bd631471","correo":"20221061@uthh.edu.mx","ip_cliente":"::ffff:127.0.0.1","fecha_hora":"21/7/2025, 6:14:56"}
[21/7/2025, 6:15:03] INFO: Sesi칩n cerrada {"ip_cliente":"::ffff:127.0.0.1"}
[21/7/2025, 6:15:23] INFO: Inicio de sesi칩n exitoso {"usuario_id":"aa7aeedc-9050-4532-bca4-3993bd631471","correo":"20221061@uthh.edu.mx","ip_cliente":"::ffff:127.0.0.1","fecha_hora":"21/7/2025, 6:15:23"}
[21/7/2025, 6:19:05] INFO: Sesi칩n cerrada {"ip_cliente":"::ffff:127.0.0.1"}
[21/7/2025, 6:19:12] INFO: Sesi칩n cerrada {"ip_cliente":"::ffff:127.0.0.1"}
[21/7/2025, 6:21:31] INFO: Sesi칩n cerrada {"ip_cliente":"::ffff:127.0.0.1"}
[21/7/2025, 6:22:03] INFO: Inicio de sesi칩n exitoso {"usuario_id":"aa7aeedc-9050-4532-bca4-3993bd631471","correo":"20221061@uthh.edu.mx","ip_cliente":"::ffff:127.0.0.1","fecha_hora":"21/7/2025, 6:22:03"}
[21/7/2025, 6:22:15] INFO: Sesi칩n cerrada {"ip_cliente":"::ffff:127.0.0.1"}
[21/7/2025, 6:24:44] INFO: Inicio de sesi칩n exitoso {"usuario_id":"aa7aeedc-9050-4532-bca4-3993bd631471","correo":"20221061@uthh.edu.mx","ip_cliente":"::ffff:127.0.0.1","fecha_hora":"21/7/2025, 6:24:44"}
[21/7/2025, 12:42:30] INFO: Inicio de sesi칩n exitoso {"usuario_id":"aa7aeedc-9050-4532-bca4-3993bd631471","correo":"20221061@uthh.edu.mx","ip_cliente":"::1","fecha_hora":"21/7/2025, 12:42:30"}
[21/7/2025, 13:31:23] CRITICAL: Fallo al iniciar el servidor o conectar a la base de datos {"codigo_error":"SERVER_START_FAIL","fecha_hora":"21/7/2025, 13:31:23","stack":"SequelizeHostNotFoundError: getaddrinfo ENOTFOUND dpg-d13h7bre5dus73eoma4g-a.oregon-postgres.render.com\n    at Client._connectionCallback (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:136:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\client.js:326:19)\n    at Client._handleErrorEvent (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Connection.emit (node:events:518:28)\n    at Socket.reportStreamError (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\connection.js:57:12)\n    at Socket.emit (node:events:518:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","ip_servidor":"localhost"}
[21/7/2025, 13:34:40] CRITICAL: Fallo al iniciar el servidor o conectar a la base de datos {"codigo_error":"SERVER_START_FAIL","fecha_hora":"21/7/2025, 13:34:40","stack":"SequelizeHostNotFoundError: getaddrinfo ENOTFOUND dpg-d13h7bre5dus73eoma4g-a.oregon-postgres.render.com\n    at Client._connectionCallback (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:136:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\client.js:326:19)\n    at Client._handleErrorEvent (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Connection.emit (node:events:518:28)\n    at Socket.reportStreamError (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\connection.js:57:12)\n    at Socket.emit (node:events:518:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","ip_servidor":"localhost"}
[21/7/2025, 13:35:27] CRITICAL: Fallo al iniciar el servidor o conectar a la base de datos {"codigo_error":"SERVER_START_FAIL","fecha_hora":"21/7/2025, 13:35:27","stack":"SequelizeHostNotFoundError: getaddrinfo ENOTFOUND dpg-d13h7bre5dus73eoma4g-a.oregon-postgres.render.com\n    at Client._connectionCallback (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:136:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\client.js:326:19)\n    at Client._handleErrorEvent (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Connection.emit (node:events:518:28)\n    at Socket.reportStreamError (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\connection.js:57:12)\n    at Socket.emit (node:events:518:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","ip_servidor":"localhost"}
[21/7/2025, 13:35:36] CRITICAL: Fallo al iniciar el servidor o conectar a la base de datos {"codigo_error":"SERVER_START_FAIL","fecha_hora":"21/7/2025, 13:35:36","stack":"SequelizeHostNotFoundError: getaddrinfo ENOTFOUND dpg-d13h7bre5dus73eoma4g-a.oregon-postgres.render.com\n    at Client._connectionCallback (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:136:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\client.js:326:19)\n    at Client._handleErrorEvent (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Connection.emit (node:events:518:28)\n    at Socket.reportStreamError (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\connection.js:57:12)\n    at Socket.emit (node:events:518:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","ip_servidor":"localhost"}
[21/7/2025, 13:35:46] CRITICAL: Fallo al iniciar el servidor o conectar a la base de datos {"codigo_error":"SERVER_START_FAIL","fecha_hora":"21/7/2025, 13:35:46","stack":"SequelizeHostNotFoundError: getaddrinfo ENOTFOUND dpg-d13h7bre5dus73eoma4g-a.oregon-postgres.render.com\n    at Client._connectionCallback (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:136:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\client.js:326:19)\n    at Client._handleErrorEvent (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Connection.emit (node:events:518:28)\n    at Socket.reportStreamError (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\connection.js:57:12)\n    at Socket.emit (node:events:518:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","ip_servidor":"localhost"}
