[13/10/2025, 15:30:57] CRITICAL: Fallo al iniciar el servidor o conectar a la base de datos {"codigo_error":"SERVER_START_FAIL","fecha_hora":"13/10/2025, 15:30:57","stack":"SequelizeHostNotFoundError: getaddrinfo ENOTFOUND dpg-d3anbg75r7bs73d6n0ng-a.oregon-postgres.render.com\n    at Client._connectionCallback (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:136:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\client.js:326:19)\n    at Client._handleErrorEvent (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Connection.emit (node:events:524:28)\n    at Socket.reportStreamError (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\connection.js:57:12)\n    at Socket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","ip_servidor":"localhost"}
