[25/9/2025, 10:55:14] CRITICAL: Fallo al iniciar el servidor o conectar a la base de datos {"codigo_error":"SERVER_START_FAIL","fecha_hora":"25/9/2025, 10:55:14","stack":"SequelizeConnectionError: Connection terminated unexpectedly\n    at Client._connectionCallback (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:149:20)\n    at Connection.<anonymous> (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\client.js:144:18)\n    at Object.onceWrapper (node:events:632:28)\n    at Connection.emit (node:events:518:28)\n    at Socket.<anonymous> (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\connection.js:62:12)\n    at Socket.emit (node:events:530:35)\n    at TCP.<anonymous> (node:net:343:12)","ip_servidor":"localhost"}
[25/9/2025, 11:17:27] CRITICAL: Fallo al iniciar el servidor o conectar a la base de datos {"codigo_error":"SERVER_START_FAIL","fecha_hora":"25/9/2025, 11:17:27","stack":"SequelizeHostNotFoundError: getaddrinfo ENOTFOUND dpg-d3anbg75r7bs73d6n0ng-a\n    at Client._connectionCallback (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:136:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\client.js:326:19)\n    at Client._handleErrorEvent (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Connection.emit (node:events:518:28)\n    at Socket.reportStreamError (C:\\Users\\luishdez\\Desktop\\puntoshein\\backend\\node_modules\\pg\\lib\\connection.js:57:12)\n    at Socket.emit (node:events:518:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","ip_servidor":"localhost"}
